//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Trafikverket_API.Models
{

    [XmlRoot("ORIONML")]
    public partial class trafiklageORIONML
    {

        private trafiklageORIONMLRESPONSE[] rESPONSEField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESPONSE", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public trafiklageORIONMLRESPONSE[] RESPONSE
        {
            get
            {
                return this.rESPONSEField;
            }
            set
            {
                this.rESPONSEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    [XmlRoot("RESPONSE")]
    public partial class trafiklageORIONMLRESPONSE
    {

        private Trafiklage[] lpvTrafiklagenField;

        private string localeField;

        private string pluginField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Trafiklage", typeof(Trafiklage), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public Trafiklage[] LpvTrafiklagen
        {
            get
            {
                return this.lpvTrafiklagenField;
            }
            set
            {
                this.lpvTrafiklagenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string plugin
        {
            get
            {
                return this.pluginField;
            }
            set
            {
                this.pluginField = value;
            }
        }
    }

    [XmlRoot("Trafiklage")]
    public partial class Trafiklage
    {

        private string utgangsdatumField;

        private string tagGruppField;

        private string trafikInfoAgareNamnField;

        private string trafikInfoAgareUrlField;

        private string trafikInfoAgareMobilUrlField;

        private string franField;

        private string tillField;

        private string trafikplatsSignaturField;

        private string trafikplatsNamnField;

        private string trafikplatsPrognosField;

        private string statiskInformationTrafikplatsVisningField;

        private string visaAnkomstField;

        private string installdAnkomstField;

        private string annonseradTidpunktAnkomstField;

        private string visaAvgangField;

        private string installdAvgangField;

        private string annonseradTidpunktAvgangField;

        private string sparangivelseAvgangField;

        private string anmarkningarAvgangField;

        private string arAvgangTagField;

        private string senasteTidrapportTidpunktField;

        private string senasteTidrapportTrafikplatsField;

        private string senasteTidrapportAktivitetField;

        private string teknisktTagIdField;

        private string annonseratTagIdField;

        private string arAnkomstTagField;

        private string sparangivelseAnkomstField;

        private string anmarkningarAnkomstField;

        private string tagGruppOrdningField;

        private string annonseradAnkomstTidField;

        private string annonseradAvgangTidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Utgangsdatum
        {
            get
            {
                return this.utgangsdatumField;
            }
            set
            {
                this.utgangsdatumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TagGrupp
        {
            get
            {
                return this.tagGruppField;
            }
            set
            {
                this.tagGruppField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrafikInfoAgareNamn
        {
            get
            {
                return this.trafikInfoAgareNamnField;
            }
            set
            {
                this.trafikInfoAgareNamnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrafikInfoAgareUrl
        {
            get
            {
                return this.trafikInfoAgareUrlField;
            }
            set
            {
                this.trafikInfoAgareUrlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrafikInfoAgareMobilUrl
        {
            get
            {
                return this.trafikInfoAgareMobilUrlField;
            }
            set
            {
                this.trafikInfoAgareMobilUrlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Fran
        {
            get
            {
                return this.franField;
            }
            set
            {
                this.franField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Till
        {
            get
            {
                return this.tillField;
            }
            set
            {
                this.tillField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrafikplatsSignatur
        {
            get
            {
                return this.trafikplatsSignaturField;
            }
            set
            {
                this.trafikplatsSignaturField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrafikplatsNamn
        {
            get
            {
                return this.trafikplatsNamnField;
            }
            set
            {
                this.trafikplatsNamnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrafikplatsPrognos
        {
            get
            {
                return this.trafikplatsPrognosField;
            }
            set
            {
                this.trafikplatsPrognosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StatiskInformationTrafikplatsVisning
        {
            get
            {
                return this.statiskInformationTrafikplatsVisningField;
            }
            set
            {
                this.statiskInformationTrafikplatsVisningField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VisaAnkomst
        {
            get
            {
                return this.visaAnkomstField;
            }
            set
            {
                this.visaAnkomstField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InstalldAnkomst
        {
            get
            {
                return this.installdAnkomstField;
            }
            set
            {
                this.installdAnkomstField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AnnonseradTidpunktAnkomst
        {
            get
            {
                return this.annonseradTidpunktAnkomstField;
            }
            set
            {
                this.annonseradTidpunktAnkomstField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VisaAvgang
        {
            get
            {
                return this.visaAvgangField;
            }
            set
            {
                this.visaAvgangField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InstalldAvgang
        {
            get
            {
                return this.installdAvgangField;
            }
            set
            {
                this.installdAvgangField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AnnonseradTidpunktAvgang
        {
            get
            {
                return this.annonseradTidpunktAvgangField;
            }
            set
            {
                this.annonseradTidpunktAvgangField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SparangivelseAvgang
        {
            get
            {
                return this.sparangivelseAvgangField;
            }
            set
            {
                this.sparangivelseAvgangField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AnmarkningarAvgang
        {
            get
            {
                return this.anmarkningarAvgangField;
            }
            set
            {
                this.anmarkningarAvgangField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ArAvgangTag
        {
            get
            {
                return this.arAvgangTagField;
            }
            set
            {
                this.arAvgangTagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SenasteTidrapportTidpunkt
        {
            get
            {
                return this.senasteTidrapportTidpunktField;
            }
            set
            {
                this.senasteTidrapportTidpunktField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SenasteTidrapportTrafikplats
        {
            get
            {
                return this.senasteTidrapportTrafikplatsField;
            }
            set
            {
                this.senasteTidrapportTrafikplatsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SenasteTidrapportAktivitet
        {
            get
            {
                return this.senasteTidrapportAktivitetField;
            }
            set
            {
                this.senasteTidrapportAktivitetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TeknisktTagId
        {
            get
            {
                return this.teknisktTagIdField;
            }
            set
            {
                this.teknisktTagIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AnnonseratTagId
        {
            get
            {
                return this.annonseratTagIdField;
            }
            set
            {
                this.annonseratTagIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ArAnkomstTag
        {
            get
            {
                return this.arAnkomstTagField;
            }
            set
            {
                this.arAnkomstTagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SparangivelseAnkomst
        {
            get
            {
                return this.sparangivelseAnkomstField;
            }
            set
            {
                this.sparangivelseAnkomstField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AnmarkningarAnkomst
        {
            get
            {
                return this.anmarkningarAnkomstField;
            }
            set
            {
                this.anmarkningarAnkomstField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TagGruppOrdning
        {
            get
            {
                return this.tagGruppOrdningField;
            }
            set
            {
                this.tagGruppOrdningField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AnnonseradAnkomstTid
        {
            get
            {
                return this.annonseradAnkomstTidField;
            }
            set
            {
                this.annonseradAnkomstTidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AnnonseradAvgangTid
        {
            get
            {
                return this.annonseradAvgangTidField;
            }
            set
            {
                this.annonseradAvgangTidField = value;
            }
        }
    }
}